export {HomeIcon} from './icons/HomeIcon'
export {GamepadIcon} from './icons/GamepadIcon'
export {PrizeIcon} from './icons/PrizeIcon'
export {RouteIcon} from './icons/RouteIcon'
export {FaceHappyIcon} from './icons/FaceHappyIcon'